../../src/rtl/VERILOG_TEMPLATE/VERILOG_TEMPLATE.v
../../src/rtl/VERILOG_TEMPLATE/VT_CORE/VT_CORE.v
../../src/rtl/VERILOG_TEMPLATE/VT_CORE/VT_CORE_GAIN.v
../../src/rtl/VERILOG_TEMPLATE/VT_CORE/VT_CORE_CAPTURE.v
../../src/rtl/VERILOG_TEMPLATE/VT_REG/VT_REG.v
